### ISSUE TITLE
Context Manager is Empty On Opening

### ISSUE THREAD

**Issue by weiweihuanghuang** [HugoJourdan/Context-Manager#1]
Using 3.2 (3179)
When I open Context Manager for the first time, this is what I get when selecting the letter /H for example:

<img width="806" alt="Screen Shot 2023-02-28 at 12 10 07 pm" src="https://user-images.githubusercontent.com/1271897/221726292-fe7d7281-9a4a-470b-a447-deca3e24fde6.png">

When I try to create classes, it can only add the letter G for some reason no matter what glyph is selected in the edit view:
<img width="806" alt="Screen Shot 2023-02-28 at 12 10 18 pm" src="https://user-images.githubusercontent.com/1271897/221726407-cfc535ab-a086-4589-96df-563ca89c0dad.png">

Am I using this wrong?

**Comment by weiweihuanghuang** [comment]
When I try to import the file inside the plugin `~/Library/Application Support/Glyphs 3/Repositories/Context-Manager/Context Manager.glyphsPlugin/Contents/Resources/ContextManager.json` I get this error:

```
Details:
Traceback (most recent call last):

  File "vanillaBase.py", line 514, in action_
    self.callback(sender)

  File "plugin.py", line 798, in importContextDataCallback
    glyphName = Glyphs.font.glyphs[GLYPH].name

AttributeError: 'NoneType' object has no attribute 'name'

App:3.2-3179 Plugin:(null)-(null) System:11.6.1
```

Is this a vanilla issue @schriftgestalt

**Comment by HugoJourdan** [comment]
@weiweihuanghuang 
> When I open Context Manager for the first time, this is what I get when selecting the letter /H for example:  

It's seem that default file miss some datas, I will fix it


> When I try to create classes, it can only add the letter G for some reason no matter what glyph is selected in the edit view:

Only selected glyphs in FontView are added, I'll change this to also work with selectedLayers (this is better).

> When I try to import the file inside the plugin ~/Library/Application Support/Glyphs 3/Repositories/Context-Manager/Context Manager.glyphsPlugin/Contents/Resources/ContextManager.json I get this error:

This is not a vanilla problem, it happens when I try to import data from glyphs that are not in the current font.
To avoid this, I should look for the data in GlyphData.xml instead of currentFont. I will fix it temporarily

**Comment by weiweihuanghuang** [comment]
I'm still getting an empty list when I open the plugin

**Comment by HugoJourdan** [comment]
Sorry @weiweihuanghuang, I didn't find time to fix it. 
I will try to work on it this weekend.
