### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by schriftgestalt** [HugoJourdan/Context-Manager#2]
I got this crash report from a user:
```
Details:
Traceback (most recent call last):

  File "vanillaBase.py", line 514, in action_
    self.callback(sender)

  File "plugin.py", line 605, in add_remove_contextGlyphCallBack
    i = self.w.tabs[1].listOfContextClass.getSelection()[0]

IndexError: list index out of range

App:3.2-3179 Plugin:(null)-(null) System:11.6.1
```

**Comment by schriftgestalt** [comment]
another one:
```
Details:
Traceback (most recent call last):

 File "GlyphsApp/GlyphsApp/__init__.py", line 1380, in callback_

 File "plugin.py", line 453, in openWindow_
   self.updateWindow()

 File "plugin.py", line 405, in updateWindow
   tab1.contextClassList.set(self.jsonFile["Glyph"][glyphName]["ContextClass"])

KeyError: 'a.alt6'
```

**Comment by schriftgestalt** [comment]
```
Details:
Traceback (most recent call last):

 File "GlyphsApp/GlyphsApp/__init__.py", line 1494, in callback_

 File "plugin.py", line 453, in openWindow_
   self.updateWindow()

 File "plugin.py", line 405, in updateWindow
   tab1.contextClassList.set(self.jsonFile["Glyph"][glyphName]["ContextClass"])
                             ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^

KeyError: 'aacute.002'

App:3.3.1-3343 System:15.6.1 Python:3.11 Plugin:1.0-1.0
```
